spring:
  application:
    name: "QuickstartApplication"
  config:
    activate.on-profile: default
server:
  port: ${PORT:8080}
---
spring:
  application:
    name: "QuickstartApplication"
  config:
    activate.on-profile: gcp
    import: sm://
server:
  port: ${PORT:8080}
